# Site settings
title: 2023 '청춘'이 '청춘'에게
email: junsu0529@gmail.com
url: https://junsu0529.github.io/
description: 청춘인 사람들, 청춘이었던 사람들, 이제 청춘일 모든 사람들 중 한 명의 청춘인 당신을 초대합니다. 
keywords: "청춘, 도전"
skills: "청춘이란 인생의 어떤 기간이 아니라 마음의 상태를 말한다.<br><br>
         '청춘'이라는 주제로 음감회, 상영회를 진행합니다.<br>
         (1) 음감회: [앨범명] 착륙 버튼 없는 여행 (6 Track)<br> 
         (2) 상영회: [영화제목] 무인사진관"
meta_author: Junsu Lee

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Junsu Lee
  location: Date & Location
  social: Visit Us More
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/kooooo_koo
  - title: youtube
    url: https://www.youtube.com/@u_makase
  - title: youtube
    url: https://www.youtube.com/@visualpoemeyes
  - title: github
    url: http://github.com/junsu0529

# Postal address (add as many lines as necessary)
address:
  - line: 2023. 10. 13. (금), 19:30 ~ 21:00
  - line: 홍대 스페이스M (마포구 양화로15길 17)

# Credits content
credits: '<착륙 버튼 없는 여행><br>하마립스 으마카세 쏭해<br><br><무인 사진관><br>구경석<br>이문주 윤정 이재성'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
